### ISSUE TITLE
use StableDiffusion3Pipeline but got error

### ISSUE THREAD

**Issue by qingchen177** [Stability-AI/sd3.5#12]
this is my code:
```python
import torch
from diffusers import `StableDiffusion3Pipeline`

pipe = StableDiffusion3Pipeline.from_pretrained("/home/user/work/models/origin-models/AI-ModelScope/stable-diffusion-3___5-large-turbo/", torch_dtype=torch.bfloat16)
pipe = pipe.to("cuda")

image = pipe(
    "A capybara holding a sign that reads Hello Fast World",
    num_inference_steps=4,
    guidance_scale=0.0,
).images[0]
image.save("capybara.png")

```
this is error:
```shell
Cannot initialize model with low cpu memory usage because `accelerate` was not found in the environment. Defaulting to `low_cpu_mem_usage=False`. It is strongly recommended to install `accelerate` for faster and less memory-intense model loading. You can do so with: 

pip install accelerate

.
Loading pipeline components...:  67%|██████▋   | 6/9 [00:27<00:13,  4.62s/it]
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/t2i/lib/python3.11/site-packages/diffusers/models/model_loading_utils.py", line 140, in load_state_dict
    file_extension = os.path.basename(checkpoint_file).split(".")[-1]
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen posixpath>", line 142, in basename
TypeError: expected str, bytes or os.PathLike object, not NoneType

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/work/workspace/projects/python/t2i/sd3.5/demo.py", line 4, in <module>
    pipe = StableDiffusion3Pipeline.from_pretrained("/home/user/work/models/origin-models/AI-ModelScope/stable-diffusion-3___5-large-turbo/", torch_dtype=torch.bfloat16)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/anaconda3/envs/t2i/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/user/anaconda3/envs/t2i/lib/python3.11/site-packages/diffusers/pipelines/pipeline_utils.py", line 896, in from_pretrained
    loaded_sub_model = load_sub_model(
                       ^^^^^^^^^^^^^^^
  File "/home/user/anaconda3/envs/t2i/lib/python3.11/site-packages/diffusers/pipelines/pipeline_loading_utils.py", line 704, in load_sub_model
    loaded_sub_model = load_method(os.path.join(cached_folder, name), **loading_kwargs)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/anaconda3/envs/t2i/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/user/anaconda3/envs/t2i/lib/python3.11/site-packages/diffusers/models/modeling_utils.py", line 940, in from_pretrained
    state_dict = load_state_dict(model_file, variant=variant)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/anaconda3/envs/t2i/lib/python3.11/site-packages/diffusers/models/model_loading_utils.py", line 152, in load_state_dict
    with open(checkpoint_file) as f:
         ^^^^^^^^^^^^^^^^^^^^^
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by Eric-Hao** [comment]
@qingchen177 Using `pip install accelerate` should resolve this issue.

**Comment by qingchen177** [comment]
Thanks
