### ISSUE TITLE
SD 3.5 error

### ISSUE THREAD

**Issue by Tamila-2017** [Stability-AI/sd3.5#27]
Hi,

I am executing these commands to install SD 3.5:

```
# Generate a cat using SD3.5 Large model (at models/sd3.5_large.safetensors) with its default settings
python3 sd3_infer.py --prompt "cute wallpaper art of a cat"
```

but an error immediately occurs:
```
.sd3.5) test@servr:~/Stable Diffusion/sd3.5$ python3 sd3_infer.py --prompt "cute wallpaper art of a cat" --model models/sd3.5_large.safetensors
Loading tokenizers...
You are using the default legacy behaviour of the <class 'transformers.models.t5.tokenization_t5.T5Tokenizer'>. This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=False`. This should only be set if you understand what it means, and thoroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565
Loading Google T5-v1-XXL...
Traceback (most recent call last):
  File "/home/test/Stable Diffusion/sd3.5/sd3_infer.py", line 654, in <module>
    fire.Fire(main)
  File "/home/test/Stable Diffusion/sd3.5/.sd3.5/lib/python3.11/site-packages/fire/core.py", line 135, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/test/Stable Diffusion/sd3.5/.sd3.5/lib/python3.11/site-packages/fire/core.py", line 468, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
                                ^^^^^^^^^^^^^^^^^^^^
  File "/home/test/Stable Diffusion/sd3.5/.sd3.5/lib/python3.11/site-packages/fire/core.py", line 684, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/test/Stable Diffusion/sd3.5/.sd3.5/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/test/Stable Diffusion/sd3.5/sd3_infer.py", line 602, in main
    inferencer.load(
  File "/home/test/Stable Diffusion/sd3.5/sd3_infer.py", line 275, in load
    self.t5xxl = T5XXL(model_folder, text_encoder_device, torch.float32)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/test/Stable Diffusion/sd3.5/sd3_infer.py", line 128, in __init__
    with safe_open(
         ^^^^^^^^^^
FileNotFoundError: No such file or directory: "models/t5xxl.safetensors"
(.sd3.5) test@server:~/Stable Diffusion/sd3.5$ 
```

**Comment by Against-the-Wind** [comment]
Try downloading the checkpoint of the t5xxl model from huggingface into your models folder and change the file name into t5xxl.safetensors
https://huggingface.co/stabilityai/stable-diffusion-3.5-large/blob/main/text_encoders/t5xxl_fp16.safetensors
